epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - http: '0.0.0.0:40772'
  mounts:
    /mira-tuners:
      path: /var/www/mira-tuners
      index: index.html

channels:
  # Add channels of interest.
  - name: NHK
    type: GR
    channel: '27'

tuners:
  # Add tuners available on a local machine.
  - name: Tuner0
    types: [GR]
    command: >-
      recisdb tune --device /dev/px4video2 --channel {{{channel}}} {{{extra_args}}} -
